---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

## Use single node discovery in order to disable production mode and avoid bootstrap checks
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#
discovery.type: single-node

# Set to true to enable X-Pack security on the node. 
# xpack.security.enabled: true
xpack.security.enabled: false

# Enable auditing to keep track of attempted 
# and successful interactions with Elasticsearch cluster 
# events are logged to a dedicated elasticsearch-access.log file 
# xpack.security.audit.enabled: true
xpack.security.audit.enabled: false

# xpack.license.self_generated.type: trial
